# Generated by Django 4.2.30 on 2026-07-03 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agencia', models.CharField(default='0001', max_length=5)),
                ('numero', models.CharField(max_length=10, unique=True)),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('limite', models.DecimalField(decimal_places=2, default=1000, max_digits=12)),
                ('status', models.CharField(choices=[('ATIVA', 'Ativa'), ('BLOQUEADA', 'Bloqueada'), ('ENCERRADA', 'Encerrada')], default='ATIVA', max_length=20)),
                ('data_abertura', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conta', to='core.cliente')),
            ],
        ),
    ]
