# Generated by Django 4.2.30 on 2026-07-03 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_conta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conta',
            name='data_abertura',
        ),
        migrations.RemoveField(
            model_name='conta',
            name='limite',
        ),
        migrations.RemoveField(
            model_name='conta',
            name='status',
        ),
        migrations.AddField(
            model_name='conta',
            name='ativa',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='conta',
            name='cliente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.cliente'),
        ),
    ]
