# Generated by Django 4.2.30 on 2026-07-03 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_conta_data_abertura_remove_conta_limite_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('DEPOSITO', 'Depósito'), ('SAQUE', 'Saque'), ('PIX', 'PIX'), ('TRANSFERENCIA', 'Transferência')], max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descricao', models.CharField(blank=True, max_length=200)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='core.conta')),
            ],
        ),
    ]
